services:
  tflow-api:
    build: .
    container_name: tflow_api
    restart: unless-stopped
    ports:
      - "6969:6969"
    env_file:
      - .env
    networks:
      - shared_pg_network

networks:
  shared_pg_network:
    external: true
